// The service worker is generated by `next build` as a prerendered route. On Cloudflare, static
// files are served straight from the assets folder (never touching the Worker), so copy it there.
import { copyFileSync, existsSync, mkdirSync } from "node:fs";

const from = ".next/server/app/serwist";
const to = ".open-next/assets/serwist";
if (!existsSync(`${from}/sw.js.body`)) throw new Error("sw.js was not generated by next build");
mkdirSync(to, { recursive: true });
copyFileSync(`${from}/sw.js.body`, `${to}/sw.js`);
if (existsSync(`${from}/sw.js.map.body`)) copyFileSync(`${from}/sw.js.map.body`, `${to}/sw.js.map`);
console.log("Copied service worker to", to);
